### ISSUE TITLE
How do you login?

### ISSUE THREAD

**Issue by Zacky2613** [nathan-yan/courier#2]
I'm so confused, there is no register page nor a "correct" login answer, and the README.md doesn't provide anything just saying "you will be asked to login if it is your first time" and **nothing else about how to login.** This seems like a *really* cool project. To bad I can't even login to access anything..

**Comment by Zacky2613** [comment]
I am a dumbass. I am so sorry (login with facebook)

**Comment by nathan-yan** [comment]
Hey! Yeah sorry the documentation is pretty bad haha. I will say that since making this, the fbchat unofficial API this project is based on would not let me log in anymore, so I basically consider this project dead until some more stable solution comes along.

**Comment by Zacky2613** [comment]
Thanks for the quick reply! Again, so sorry for the dumb issue and how rude I was (I was just a little frustrated). But yes, as you stated the login doesn't work anymore (I was in the middle of typing a IndexError issue with the login just as you sent this). Massive props on you for making this by the way! Seems like a really cool project when it functioned!

Maybe update the README with a note about its current state?

**Comment by nathan-yan** [comment]
It was cool while it lasted 🥲. And yes, good idea about the README, will make a change real quick
